sudo: required
language: java
install: true

jobs:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8

before_install:
  - ./start-broker.sh

script:
  - mvn -B clean -q
  - mvn -B --projects org.eclipse.paho.client.mqttv3,org.eclipse.paho.client.mqttv3.test test -q
  - mvn -B --projects org.eclipse.paho.mqttv5.client,org.eclipse.paho.mqttv5.client.test test -q

